platform :ios, '10.0'

target 'basicPOS_Example' do
  use_frameworks!
  pod 'basicPOS', :path => '../'

  target 'UnitTests' do
    inherit! :search_paths

    pod 'basicPOS', :path => '../'
    pod 'Quick'
    pod 'Nimble'
  end
end
